### PR TITLE
Renamed terminology

### PR DESCRIPTION
**Pull request by Anne-Linde**

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Hi @Anne-Linde.
For most of the folders I can guess how you renamed them, but for the following folders I am not sure:

- Actigraph_pro3
- Activpal_pro2
- Activpal_pro3
- GENEActiv_pro3
- Shimmer_pro2_ses3A
- Shimmer_pro2_ses3B
- Shimmer_pro3

**Comment by vincentvanhees** [comment]
It may be easiest if you could send me a list of all the folder names you have.

**Comment by Anne-Linde** [comment]
I send you a zip file with the renamed folders!

**Comment by vincentvanhees** [comment]
Hi @Anne-Linde 
I have not been able to finish testing everything, but here is one observations so far:

In "data_description_v5.xslx" I previously had the experiment value re-named to be "ms_mfcr" instead of "box", and the mechanical shaker frequency for that line needs to be set at -2, such that this timewindow is not excluded from the data.

Also, we would need to remove lines
```
}
      if (experiment == "box") {
```
from loaddata.R.

I did this because the auto-calibration script expects the "box"-experiment data to be part of "ms_mfcr", without the box data it doesn't generate meaningful output.

The alternative solution would be to use `experiments_to_extract <- "box"` inside main.R, but that does not seem to work at the moment. Should it work?

**Comment by vincentvanhees** [comment]
To have a record in the repo of how the folder names were renamed, I am now using the following script:

```
# alternatingly old and new name

foldernames = c("Actigraph_pro1", "Actigraph_timer_check",
          "Actigraph_pro2_ses1", "Actigraph_ms_hfcr",
          "Actigraph_pro2_ses2", "Actigraph_ms_lfcr",
          "Actigraph_pro2_ses3", "Actigraph_ms_mfcr",
          "Actigraph_pro3", "Actigraph_ms_bag",
          "Activpal_pro1", "Activpal_timer_check",
          "Activpal_pro2", "Activpal_ms_cr",
          "Activpal_pro3", "Activpal_ms_bag",
          "Acttrust_Condor", "Acttrust_Condor",
          "Axivity_pro1", "Axivity_timer_check",
          "Axivity_pro2_ses1", "Axivity_ms_hfcr",
          "Axivity_pro2_ses2", "Axivity_ms_lfcr",
          "Axivity_pro2_ses3", "Axivity_ms_mfcr",
          "Axivity_pro3_ses1", "Axivity_ms_hfmr",
          "Axivity_pro3_ses2", "Axivity_ms_lfmr",
          "Axivity_pro3_ses3", "Axivity_ms_bag",
          "Fitbit", "Fitbit",
          "GENEActiv_pro1", "GENEActiv_timer_check",
          "GENEActiv_pro2_ses1", "GENEActiv_ms_hfcr",
          "GENEActiv_pro2_ses2", "GENEActiv_ms_lfcr",
          "GENEActiv_pro2_ses3", "GENEActiv_ms_mfcr",
          "GENEActiv_pro3", "GENEActiv_ms_bag",
          "MOX_exportedCSV/exportedCSV/MOX_pro1", "MOX_exportedCSV/exportedCSV/MOX_timer_check",
          "MOX_exportedCSV/exportedCSV/MOX_pro2_ses1", "MOX_exportedCSV/exportedCSV/MOX_ms_hfcr",
          "MOX_exportedCSV/exportedCSV/MOX_pro2_ses2", "MOX_exportedCSV/exportedCSV/MOX_ms_lfcr",
          "MOX_exportedCSV/exportedCSV/MOX_pro2_ses3", "MOX_exportedCSV/exportedCSV/MOX_mfcr",
          "MOX_exportedCSV/exportedCSV/MOX_pro3", "MOX_exportedCSV/exportedCSV/MOX_ms_bag",
          "Shimmer_pro1", "Shimmer_timer_check",
          "Shimmer_pro2_ses1", "Shimmer_ms_hfcr",
          "Shimmer_pro2_ses2", "Shimmer_ms_lfcr",
          "Shimmer_pro2_ses3A", "Shimmer_ms_mfcrA",
          "Shimmer_pro2_ses3B", "Shimmer_ms_mfcrB",
          "Shimmer_pro3", "Shimmer_ms_bag")

path = "/home/vincent/data/VUMC/shaker_experiments/unstructured_raw_data/"
foldernames = paste0(path, foldernames)
N = length(foldernames)
file.rename(from = foldernames[seq(1, N, by = 2)], to = foldernames[seq(2, N, by = 2)])

```

**Pull request merged**
