### PR TITLE
Structure analyses per experiments and latest updates

### PR DESCRIPTION
**Pull request by Anne-Linde**
Checklist before merging:

- [ ] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [ ] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [ ] Updated or expanded the documentation.
- [ ] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [ ] Added your name to the contributors lists in the `DESCRIPTION` file.

### CODE REVIEW

**Review by vincentvanhees — COMMENTED** [review]
Hi Annelinde, looks great. I know you have spent a lot of time on this so feel free to ignore, but maybe you find the following suggestions useful:

## 1. Rename a few functions
It may be good to rename a few functions as follows to make it easier to spot their relation to the parts of the paper (SDC = Supplemental Digital Content):

Current name | New name 
----------------|---------------
sampling_rate_analyses.R | sampling_rate_analyses_E5.R
time_keeping.R | time_keeping_SDC1.R
noise_analyses.R | noisse_analyses_SDC2.R
main.R | structure_data.R

## 2. Update README

Update README to provide a brief pointer to how this repository has been used. For example just add bullet points:

1. We structured the raw input files with `inst/researchcode/structure_data.R`.
2. We then ran the evaluations as discussed in the paper with the .Rmd files as can be found in `inst/researchcode`.

## 3. Move old functions to new `oldcode` folder

There are a couple of files in directory researchcode that are no longer used for the paper:

- metrics_analyses.R
- non_wear_analyses.R
- derive_calibration_coefficients.R
- renaming_folders.R

Keeping these may be confusing for someone who tries to understand the paper, throwing them away may also be frustrating if we or someone else wants to continue that work, while storing them somewhere else could cause them to be lost. So, my proposal is to move them to a new folder inst/oldcode. In that way they can be found but it is very clear that it has nothing to do with the paper or ongoing work.

## 4. Moving function files to R folder

Would it be possible to move `frequency_domain_functions.R` and `time_domain_functions.R` to the R folder. In that way all functions can be found there and documentation for them will be part of the package documentation. The added advantage is that the `inst/researchcode` folder is limited to just the R/Rmd scripts used to use all those functions.

**Comment by Anne-Linde** [comment]
@vincentvanhees Ik zie dat dezelfde test faalt als de vorige keer, er is een v2 nodig, ik weet alleen niet hoe dit op te lossen, zie jij hoe dit gedaan kan worden?

**Comment by vincentvanhees** [comment]
De .yml bestanden in .github folder moeten worden bijgewerkt:
https://github.com/wadpac/mechanicalshakerexperiments/blob/main/.github/workflows/r_basic_check.yml
https://github.com/wadpac/mechanicalshakerexperiments/blob/main/.github/workflows/r_codecov.yml

Je kunt de code uit de volgende twee in hun geheel kopiëren want er staat niets in dat package specifiek is:
https://github.com/wadpac/GGIR/blob/master/.github/workflows/r_codecov.yml
https://github.com/wadpac/GGIR/blob/master/.github/workflows/r_basic_check.yml

**Comment by Anne-Linde** [comment]
Met deze aanpassingen is het gelukt. Ik zal in een nieuwe branch de README updaten en zoals door @vincentvanhees voorgesteld herstructureren! Ook zal ik nog een aantal variabelen namen wijzigen zodat het overeenkomt met het artikel

**Pull request merged**
